version: "3"

services:

  rembg-app:
    # build: .
    image: alyetama/rembg-app:latest
    ports:
      - "8501:8501"
    command: >
      streamlit run streamlit_app.py
    restart: always
    volumes:
      - "./.streamlit:/home/app/.streamlit"
