version: "3"

services:

  remove_background:
    # build: .
    image: remove-background:latest
    ports:
      - "8090:8090"
    command: "streamlit run streamlit_app.py"
    restart: always
    volumes:
      - "./.streamlit:/home/app/.streamlit"
