name: Docker Build

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  IMAGE_NAME: rembg-app

jobs:
  ghcr:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Compute short SHA 
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build image
        run: |
          echo "Build: ${SHORT_SHA}"
          docker build . --file Dockerfile \
            --tag "${IMAGE_NAME}" \
            --label "runnumber=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          echo IMAGE_ID=$IMAGE_ID

          docker tag ${IMAGE_NAME} $IMAGE_ID:$SHORT_SHA
          docker push $IMAGE_ID:$SHORT_SHA

  dockerhub:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Compute short SHA 
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.SHORT_SHA }},${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
